services:
  rosplat:
    container_name: rosplat
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    image: rosplat:lyrical-cuda13.3
    init: true
    network_mode: "host"
    ipc: host
    user: "${USER_UID:-1000}:${USER_GID:-1000}"
    stdin_open: true
    tty: true
    working_dir: /workspace
    devices:
      - "nvidia.com/gpu=all"
    environment:
      DISPLAY: ${DISPLAY:-:0}
      PYGLFW_LIBRARY_VARIANT: x11
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      TORCH_CUDA_ARCH_LIST: ${TORCH_CUDA_ARCH_LIST:-}
    volumes:
      - ../:/workspace
      - rosplat-cache:/home/rosplat/.cache
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

volumes:
  rosplat-cache:
